sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t coolp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true coolp/docker-react npm test

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'DockerReact'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-128937639286'
  bucket_path: 'DockerReact'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
